### ISSUE TITLE
Bug in Image Edit Copy With Selections

### ISSUE THREAD

**Issue by jeffdc** [jeffdc/gallformers#81] opened 2021-02-10 20:55 UTC
This is working well enough for me to start adding images in earnest, although it does seem to have a bit of a bug. After I close the modal to fill in one image metadata, the site doesn't recognize that I've checked that box for "Copy One to Others." But it works fine if I reload the page so not a huge issue.

_Originally posted by @Megachile in https://github.com/jeffdc/gallformers/issues/74#issuecomment-776935257_

**Comment by ahiatt14** [comment] 2021-02-11 01:41
@jeffdc I dug through the code and I dunno if there's a bug here so much as a small misunderstanding. The edit-image feature in /admin/images will show a variable number of sources available to choose from, or sometimes none. I think @Megachile was expecting to have all sources available as options all the time. It seems like sourcing an image depends on the parent organism's sources - if the organism has no sources, any images attached to it can't select any. Just going off what I see in "sourcesWithSpecieSourceBySpeciesId." Am I understanding that behavior correctly? If this is expected behavior, maybe we can add to the Sources dropdown tooltip clarifying that the organism must have sources itself

**Comment by jeffdc** [comment] 2021-02-11 14:15
Yes the list is constrained to sources that are already mapped to the species. I will add a help message to clarify. If we provide an unconstrained list of sources we would also have to replicate the species-source mapping screen to get all of the needed data so that we could persist that mapping. To be clear, an image can have 2 types of sources:

1) an "external" source which would just be a link and the other metadata fields
2) an "internal" source which is just a reference to an already exisitng species-source mapping plus the other metadata fields

I think it would be very confusing to offer the ability to map a source to an image (that is itself mapped to a species) where the source and species are not already mapped. 

It sounds like maybe what is really wanted here is a single screen to map a species to a source and then to also map the images. This could be done but it would be cluttered and possibly even more confusing. I think that the challenge here is that there are dependencies of data entry and they are not obvious (all of the recent text documentation that I have recently added was to help with this same type of issue). I am not sure how to solve this but am very open to any ideas.

**Comment by Megachile** [comment] 2021-02-11 15:24
That's totally fine and makes perfect sense, it just never occurred to me that that was what was going on so I thought it was not working for no reason. I think an explanatory note here will be just fine. 

I was thinking originally that it would be good to be able to add images along with text descriptions on the source mapping screen, but I think it's fine the way it is too.

**Comment by jeffdc** [comment] 2021-02-11 15:34
Ok. I added a note to the tooltip for the Source field in the Image edit screen saying:

> This list will only show Sources that have already been mapped to the species.

**Comment by jeffdc** [comment] 2021-02-11 15:35
Hmm. I think that this conversation is happening in the wrong issue. Seems it was meant for #80

**Comment by Megachile** [comment] 2021-02-26 07:28
I can't reproduce this anymore so I'm closing for now.

**Comment by Megachile** [comment] 2021-02-26 07:36
Spoke too soon; it happened the first time I tried to add more than 2 images at once.

**Closed** 2021-10-07 15:29 UTC
Labels: bug, good first issue, admin
