### ISSUE TITLE
Gray out other fields on Edit gall page until requirements are met

### ISSUE THREAD

**Issue by Megachile** [jeffdc/gallformers#290] opened 2021-11-07 01:15 UTC
As with #283, could we make it so the rest of the gall page is only editable once the family and host fields have been entered?

**Comment by jeffdc** [comment] 2021-11-08 16:51
This is not hard to implement but I think we would need to re-consider the page layout and the tab ordering of the fields. Abundance would need to be moved after Hosts.

**Comment by Megachile** [comment] 2021-11-08 17:57
I have no objection to that, do you?

**Comment by jeffdc** [comment] 2021-11-14 21:03
I am proposing that we close this one as will not fix. My reasoning is that I have never seen a form that does not allow you to edit optional fields until after required fields are filled and I think that this is a UX anti-pattern.

Was there a particular "bad thing" that happened because of this ability to edit optional fields before all of the required fields are filled in?

**Comment by Megachile** [comment] 2021-11-14 22:41
The problem is simply that I sometimes forget to fill in the required fields, put some time into filling in all the other fields, then lose all that effort when I realize I have to add a family or host first and refresh the page. In terms of UX anti-patterns, that outcome always feels counterintuitive and frustrating to me. Presumably other sites don't apply that condition because they don't have situations where a user would be required to use a different page and reload before they can use a required field. 


It's not a huge issue but it seemed better to make that impossible. Also helps avoid confusion for new admins who might not realize what's happening.

**Comment by jeffdc** [comment] 2021-11-15 13:40
So I think that the real fix here is not loose the info you have already input unless you select a new Species that already exists. The problem is with the Family since you can not add a new one there. Let's keep this open then with the idea to fix it more in this direction then by disabling stuff.

**Comment by Megachile** [comment] 2021-11-15 19:39
I don't see how we could fix it in that way unless we just make it so that family or host are not required to create the entry?

**Comment by jeffdc** [comment] 2021-11-25 15:43
I have changed this so that it disabled all fields until the required fields are filled. I also tweaked the layout to put all the required fields first.

**Closed** 2021-11-28 21:54 UTC
Labels: enhancement
